# Generated by Django 2.1.5 on 2019-01-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128)),
                ('course_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='courses.Course')),
                ('course_prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prereq_id', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=128)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='courses.Department')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_required', to='courses.Course')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_id', to='courses.Program')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_credits', models.IntegerField()),
                ('department_req_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_req_id', to='courses.Department')),
                ('faculty_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_req_id', to='courses.Faculty')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_id2', to='courses.Program')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_id', to='courses.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_department', to='courses.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculty', to='courses.Faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='requiredcredit',
            unique_together={('program_id', 'faculty_req_id', 'department_req_id')},
        ),
        migrations.AlterUniqueTogether(
            name='requiredcourse',
            unique_together={('program_id', 'course_required')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('program_name', 'department_id')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty_id', 'department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course_id', 'course_prereq_id')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'course_num')},
        ),
    ]
