# Generated by Django 2.1.5 on 2019-01-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'course_num')},
        ),
    ]
