# Generated by Django 2.1.5 on 2019-01-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190119_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='courses.Course')),
                ('course_prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='courses.Course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course_id', 'course_prereq_id')},
        ),
    ]
