# Generated by Django 2.1.5 on 2019-01-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190119_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='courses.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='courses.Faculty')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='courses.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='departmentprogram',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='courses.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='facultydepartment',
            unique_together={('faculty_id', 'department_id')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentprogram',
            unique_together={('department_id', 'program_id')},
        ),
    ]
