# Generated by Django 2.1.5 on 2019-01-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190120_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydepartment',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='courses.Department'),
        ),
    ]
